- name: 'Setup projects.darrentuer.net'
  hosts: all
  remote_user: admin
  become: true
  become_user: root
  become_method: sudo

  vars:
    tika_version: 3.1.0
    admin_user: admin
    efs_dns_name: fs-07f628c47bfe54902.efs.ap-southeast-2.amazonaws.com

  roles:
    - core
    - applications
    - logrotate
    - auto_update
    - swap
    - efs-mount
