- name: 'Setup projects.darrentuer.net'
  hosts: all
  remote_user: admin
  become: true
  become_user: root
  become_method: sudo

  vars:
    admin_user: admin
    efs_dns_name: fs-0bf11378f69336002.efs.ap-southeast-2.amazonaws.com

  roles:
    - core
    - applications
    - logrotate
    - auto_update
    - swap
    - efs-mount
    - webapp
    - nginx
    - letsencrypt
