<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Scripts\script001-CreateTable-ToDo.sql" />
      <EmbeddedResource Include="Scripts\script001-CreateTable-ToDo.sql" />
      <None Remove="Scripts\script002-AlterTable-ToDo-Add-columns.sql" />
      <EmbeddedResource Include="Scripts\script002-AlterTable-ToDo-Add-columns.sql" />
      <None Remove="Scripts\script003-CreateTables-Categories-bookmarks-attachments-notes-projects.sql" />
      <EmbeddedResource Include="Scripts\script003-CreateTables-Categories-bookmarks-attachments-notes-projects.sql" />
      <None Remove="Scripts\script004-CreateTable-Users.sql" />
      <EmbeddedResource Include="Scripts\script004-CreateTable-Users.sql" />
      <None Remove="Scripts\script005-AlterTable-ToDo-Drop-Category.sql" />
      <EmbeddedResource Include="Scripts\script005-AlterTable-ToDo-Drop-Category.sql" />
      <None Remove="Scripts\script006-AlterTable-Notes-Add-Description.sql" />
      <EmbeddedResource Include="Scripts\script006-AlterTable-Notes-Add-Description.sql" />
      <None Remove="Scripts\script007-CreateTable-BookmarkTypes.sql" />
      <EmbeddedResource Include="Scripts\script007-CreateTable-BookmarkTypes.sql" />
    </ItemGroup>

</Project>
