---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install generic/system application packages
  package:
    name: 
      - htop
      - wget
      - curl
      - unzip
      - zip
      - git
      - build-essential
      - nfs-common
      - nfs4-acl-tools
    state: latest
