ALTER TABLE todos ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS date_created TIMESTAMPTZ NULL;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS date_modified TIMESTAMPTZ NULL;