---

- name: Install fail2ban
  apt:
    name:
      - fail2ban
    state: latest
    update_cache: yes
    lock_timeout: 300s

- name: Create jail config
  copy:
    src: 99-local-baseline.conf
    dest: /etc/fail2ban/jail.d/99-local-baseline.conf
    mode: 775

- name: Enable the service
  service:
    name: fail2ban
    enabled: yes

- name: Start the service
  service:
    name: fail2ban
    state: started